server:
  port: 30040
  shutdown: graceful
spring:
  application:
    name: ZZS-OSS
  codec:
    max-in-memory-size: 10MB
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    export:
      jmx:
        enabled: false

endpoints:
  jmx:
    enabled: false
